defaults: ../../grpo_math_1B.yaml
grpo:
  batch_multiplier: 3
  val_period: 5
  max_val_samples: 960
  val_batch_size: 960
  use_leave_one_out_baseline: false
  use_dynamic_sampling: true
  reward_scaling:
    enabled: true
    target_min: -1.0
  reward_shaping:
    enabled: true
    overlong_buffer_length: 384
    max_response_length: 3072
loss_fn:
  reference_policy_kl_penalty: 0.0
  use_importance_sampling_correction: true
  truncated_importance_sampling_type: tis
  truncated_importance_sampling_ratio: 2
  ratio_clip_max: 0.28
  ratio_clip_c: 10
checkpointing:
  checkpoint_dir: results/dapo-gemma4-31b-it-4n8g-fsdp2-automodel
  save_period: 5
policy:
  model_name: google/gemma-4-31B-it
  tokenizer:
    name: google/gemma-4-31B-it
  train_micro_batch_size: 1
  logprob_batch_size: 1
  max_total_sequence_length: 4096
  logprob_chunk_size: 4096
  offload_optimizer_for_logprob: true
  optimizer:
    name: transformer_engine.pytorch.optimizers.fused_adam.FusedAdam
    kwargs:
      lr: 1.0e-06
      weight_decay: 0.1
      master_weights: true
      store_param_remainders: true
      exp_avg_dtype: torch.bfloat16
      exp_avg_sq_dtype: torch.bfloat16
  scheduler:
  - name: torch.optim.lr_scheduler.LinearLR
    kwargs:
      start_factor: 1.0e-08
      end_factor: 1.0
      total_iters: 10
  - name: torch.optim.lr_scheduler.ConstantLR
    kwargs:
      factor: 1.0
      total_iters: 10000000000
  - milestones:
    - 10
  dtensor_cfg:
    activation_checkpointing: true
    automodel_kwargs:
      use_liger_kernel: true
      use_sdpa_patching: false
      freeze_config:
        freeze_vision_tower: true
        freeze_audio_tower: true
        freeze_language_model: false
  sequence_packing:
    enabled: false
  dynamic_batching:
    enabled: true
  make_sequence_length_divisible_by: 1
  generation:
    max_new_tokens: 3072
    vllm_cfg:
      tensor_parallel_size: 4
      gpu_memory_utilization: 0.5
    vllm_kwargs:
      language_model_only: true
data:
  max_input_seq_length: 2048
  train:
    dataset_name: DAPOMath17K
  validation:
    dataset_name: DAPOMathAIME2024
  default:
    prompt_file: null
env:
  math:
    num_workers: 16
    math_verify_impl: dapo_math_verify
logger:
  log_dir: logs/dapo-gemma4-31b-it-4n8g-fsdp2-automodel
  wandb_enabled: true
  tensorboard_enabled: true
  wandb:
    project: nemorl-gemma4
    name: dapo-gemma4-31b-it-4n8g-fsdp2-automodel
cluster:
  gpus_per_node: 8
  num_nodes: 4
