defaults: ../../grpo_math_qwen30ba3b_megatron.yaml
grpo:
  num_prompts_per_step: 16
  num_generations_per_prompt: 8
  val_period: 1000000
checkpointing:
  checkpoint_dir: results/grpo-qwen3-30ba3b-8n8g-megatron-cp2-r3
policy:
  train_global_batch_size: 128
  logprob_batch_size: 1
  make_sequence_length_divisible_by: 16
  router_replay:
    enabled: true
  sequence_packing:
    enabled: true
  megatron_cfg:
    tensor_model_parallel_size: 4
    pipeline_model_parallel_size: 2
    context_parallel_size: 2
    expert_model_parallel_size: 4
  generation:
    max_new_tokens: 2048
    vllm_cfg:
      expert_parallel_size: 4
      precision: bfloat16
      max_model_len: 4096
      enable_prefix_caching: false
    vllm_kwargs:
      enable_chunked_prefill: false
      moe_backend: triton
data:
  max_input_seq_length: 2048
data_plane:
  enabled: true
logger:
  log_dir: logs/grpo-qwen3-30ba3b-8n8g-megatron-cp2-r3
  wandb:
    name: grpo-qwen3-30ba3b-8n8g-megatron-cp2-r3
