defaults: ../../grpo_math_1B.yaml
grpo:
  use_leave_one_out_baseline: false
  reward_scaling:
    enabled: true
    target_min: -1.0
  reward_shaping:
    enabled: true
    overlong_buffer_length: 512
    max_response_length: 8192
loss_fn:
  reference_policy_kl_penalty: 0.0
  use_importance_sampling_correction: true
  truncated_importance_sampling_type: "tis"
  truncated_importance_sampling_ratio: 2
  ratio_clip_max: 0.28
  ratio_clip_c: 10
checkpointing:
  checkpoint_dir: results/grpo-qwen3.5-35ba3b-dapo-4n8g-automodel
policy:
  model_name: Qwen/Qwen3.5-35B-A3B-Base
  train_micro_batch_size: 1
  logprob_batch_size: 1
  max_total_sequence_length: 9216
  logprob_chunk_size: 4096
  offload_optimizer_for_logprob: true
  optimizer:
    name: transformer_engine.pytorch.optimizers.fused_adam.FusedAdam
    kwargs:
      lr: 1.0e-06
      weight_decay: 0.1
      master_weights: true
      store_param_remainders: true
      exp_avg_dtype: torch.bfloat16
      exp_avg_sq_dtype: torch.bfloat16
  scheduler:
  - name: torch.optim.lr_scheduler.LinearLR
    kwargs:
      start_factor: 1.0e-08
      end_factor: 1.0
      total_iters: 10
  - name: torch.optim.lr_scheduler.ConstantLR
    kwargs:
      factor: 1.0
      total_iters: 10000000000
  - milestones:
    - 10
  dtensor_cfg:
    expert_parallel_size: 32
    activation_checkpointing: true
    automodel_kwargs:
      backend:
        _target_: nemo_automodel.components.models.common.utils.BackendConfig
        attn: sdpa
        linear: torch
        rms_norm: torch
        experts: gmm
        dispatcher: deepep
        fake_balanced_gate: false
        rope_fusion: false
        enable_hf_state_dict_adapter: true
      freeze_config:
        freeze_vision_tower: true
        freeze_audio_tower: true
        freeze_language_model: false
  sequence_packing:
    enabled: false
  dynamic_batching:
    enabled: true
  generation:
    max_new_tokens: 8192
    vllm_cfg:
      tensor_parallel_size: 8
      gpu_memory_utilization: 0.5
      enforce_eager: true
data:
  max_input_seq_length: 2048
  train:
    dataset_name: DAPOMath17K
  validation:
    dataset_name: DAPOMathAIME2024
  default:
    prompt_file: null
env:
  math:
    num_workers: 16
    math_verify_impl: dapo_math_verify
logger:
  wandb_enabled: true
  tensorboard_enabled: true
  wandb:
    project: nemo-rl
    name: grpo-qwen3.5-35ba3b-dapo-4n8g-automodel
cluster:
  gpus_per_node: 8
  num_nodes: 4
