defaults: ../../grpo_math_1B.yaml
checkpointing:
  checkpoint_dir: results/grpo-qwen3.5-35ba3b-2n8g-megatron-ep16tp2cp2
policy:
  model_name: Qwen/Qwen3.5-35B-A3B-Base
  train_micro_batch_size: 1
  logprob_batch_size: 1
  max_total_sequence_length: 4096
  make_sequence_length_divisible_by: 8
  dtensor_cfg:
    enabled: false
  megatron_cfg:
    enabled: true
    tensor_model_parallel_size: 2
    context_parallel_size: 2
    sequence_parallel: true
    expert_model_parallel_size: 16
    apply_rope_fusion: false
    activation_checkpointing: true
    defer_fp32_logits: true
  generation:
    vllm_cfg:
      tensor_parallel_size: 4
      enforce_eager: true
logger:
  wandb_enabled: true
  tensorboard_enabled: true
  wandb:
    project: nemo-rl
    name: grpo-qwen3.5-35ba3b-2n8g-megatron-ep16tp2cp2
cluster:
  gpus_per_node: 8
  num_nodes: 2
