defaults: ../../ppo_gsm8k_1.5B_megatron.yaml
value:
  megatron_cfg:
    sequence_parallel: true
  dynamic_batching:
    enabled: true
checkpointing:
  checkpoint_dir: results/ppo-qwen2.5-1.5b-gsm8k-1n8g-megatron-valuetp2sp-dynbatch
logger:
  log_dir: logs/ppo-qwen2.5-1.5b-gsm8k-1n8g-megatron-valuetp2sp-dynbatch
  wandb:
    name: ppo-qwen2.5-1.5b-gsm8k-1n8g-megatron-valuetp2sp-dynbatch
