defaults: ../../ppo_math_1B_megatron.yaml
ppo:
  num_prompts_per_step: 1024
  num_generations_per_prompt: 1
  ppo_epochs: 1
  steps_per_epoch: 1
  max_num_epochs: 15
  max_num_steps: 100
  val_period: 1
  overlong_filtering: true
  reward_scaling:
    enabled: false
  reward_shaping:
    enabled: false
  adv_estimator:
    gae_lambda_policy: 1
    gae_lambda_value: 1.0
loss_fn:
  ratio_clip_max: 0.2
  ratio_clip_c: 3
value_loss_fn:
  scale: 1.0
  cliprange: 0.5
checkpointing:
  checkpoint_dir: results/ppo-qwen2.5-1.5b-gsm8k-1n8g-dtensor
policy:
  model_name: Qwen/Qwen2.5-1.5B-Instruct
  tokenizer:
    name: Qwen/Qwen2.5-1.5B-Instruct
  train_global_batch_size: 256
  train_micro_batch_size: 1
  logprob_batch_size: 1
  max_total_sequence_length: 1024
  make_sequence_length_divisible_by: ${policy.dtensor_cfg.tensor_parallel_size}
  dtensor_cfg:
    enabled: true
  megatron_cfg:
    enabled: false
  optimizer:
    name: torch.optim.AdamW
    kwargs:
      lr: 1.0e-06
      weight_decay: 0.01
      betas:
      - 0.9
      - 0.999
      eps: 1.0e-08
      foreach: false
      fused: false
  scheduler:
  - name: torch.optim.lr_scheduler.ConstantLR
    kwargs:
      factor: 1.0
      total_iters: 10000000000
  - milestones: []
  generation:
    max_new_tokens: 512
    vllm_cfg:
      max_model_len: 1024
      gpu_memory_utilization: 0.4
value:
  model_name: Qwen/Qwen2.5-1.5B-Instruct
  tokenizer:
    name: Qwen/Qwen2.5-1.5B-Instruct
  make_sequence_length_divisible_by: ${value.dtensor_cfg.tensor_parallel_size}
  reward_model_cfg:
    enabled: true
    only_head_unfreeze: false
  dtensor_cfg:
    enabled: true
  megatron_cfg:
    enabled: false
  optimizer:
    name: torch.optim.AdamW
    kwargs:
      lr: 1.0e-05
      weight_decay: 0.01
      betas:
      - 0.9
      - 0.999
      eps: 1.0e-08
      foreach: false
      fused: false
  scheduler:
  - name: torch.optim.lr_scheduler.ConstantLR
    kwargs:
      factor: 1.0
      total_iters: 10000000000
  - milestones: []
env:
  math:
    math_verify_impl: hf_math_verify
data:
  max_input_seq_length: 512
  train:
    dataset_name: gsm8k
    split: train
  validation:
    dataset_name: gsm8k
    split: test
  default:
    system_prompt_file: examples/prompts/gsm8k.txt
logger:
  log_dir: logs/ppo-qwen2.5-1.5b-gsm8k-1n8g-dtensor
  wandb_enabled: true
  wandb:
    project: nemo-rl-ppo-port-v1
    name: ppo-qwen2.5-1.5b-gsm8k-1n8g-dtensor-port
    id: ppo-qwen2_5-1p5b-gsm8k-1n8g-dtensor-port
    resume: allow
cluster:
  gpus_per_node: 8
