defaults: ../../ppo_gsm8k_1.5B_megatron.yaml
value:
  megatron_cfg:
    pipeline_model_parallel_size: 2
checkpointing:
  checkpoint_dir: results/ppo-qwen2.5-1.5b-gsm8k-1n8g-megatron-valuetp2pp2
logger:
  log_dir: logs/ppo-qwen2.5-1.5b-gsm8k-1n8g-megatron-valuetp2pp2
  wandb:
    name: ppo-qwen2.5-1.5b-gsm8k-1n8g-megatron-valuetp2pp2
